version: '3'

services:
  auth-db:
    container_name: auth-db
    image: postgres:latest
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: chris778
      POSTGRES_PASSWORD: 123456
    ports:
      - "5430:5432"
    volumes:
      - db_auth:/var/lib/postgresql/data

  rabbit_mq:
    container_name: rabbit_mq
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  db_auth: